---
- name: Install and create mysql database
  hosts: webservers
  become: yes
  vars:
    Passwd: kanyinezekiel
    DataBase: Kanyexola
    UserName: kanyexola
    RootPasswd: kanyinezekiel
  tasks:
     - name: update the client machine
       command: apt update
     - name: install mysql server
       ansible.builtin.package:
         name:
            - mysql-server
            - mysql-client
            - python3-mysqldb
            - libmysqlclient-dev
         state: latest
         update_cache: yes
     - name: start and enable mysql
       service:
            name: mysql
            state: started
     - name: Update mysql root password for all root account
       mysql_user:
         name: root
         host: "{{ item }}"
         password: "{{ RootPasswd }}"
         login_user: root
         login_password: "{{ RootPasswd }}"
         check_implicit_admin: yes
         priv: "*.*:ALL,GRANT"
       with_items:
       - "{{ ansible_hostname }}"
       - 127.0.0.1
       - ::1
       - localhost
     - name: create mysql database
       mysql_db:
         login_user: root
         login_password: "{{ RootPasswd }}"
         name: "{{ DataBase }}"
         state: present

     - name: create mysql user and set passwd and privileges
       mysql_user:
          login_user: root
          login_password: "{{ RootPasswd }}"
          name: "{{ UserName }}"
          password: "{{ Passwd }}"
          priv: "{{ DataBase }}.*:ALL"
          host: localhost
          state: present
     - name: restart mysql database
       service:
          name: mysql
          state: restarted
